apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis

---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: shorturl
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: bwbwchen/redis-lru
    ports:
    - containerPort: 6379