apiVersion: v1
kind: Service
metadata:
  name: shorturl-service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30390
    protocol: TCP
    targetPort: 8080
  selector:
    app: shorturl
