apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  type: ClusterIP
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
  selector:
    app: zookeeper

---
apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  namespace: shorturl
  labels:
    app: zookeeper
spec:
  containers:
  - name: zookeeper
    image: zookeeper:3.7.0
    ports:
    - containerPort: 2181
    volumeMounts:
    - mountPath: /data
      name: zookeeper-storage-data
    - mountPath: /datalog
      name: zookeeper-storage-datalog
  volumes:
  - name: zookeeper-storage-data
    hostPath:
      path: /home/rancher/volume/zookeeper/data
  - name: zookeeper-storage-datalog
    hostPath:
      path: /home/rancher/volume/zookeeper/datalog